
services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "443:443"
      - "587:587"
  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "80:80"