
services:
  backend:
    build:
      context: ./Backend
    container_name: Backend
    ports:
      - "8080:8080"
      - "587:587"
  frontend:
    build:
      context: ./Frontend
    container_name: Frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx
      - ./private.crt:/private.crt
      - ./public.crt:/public.crt
    depends_on:
      - backend