
services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
  frontend:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/nginx/ssl
        - ./vue-app/dist:/usr/share/nginx/html
    depends_on:
        - Backend