
services:
  backend:
    build:
      context: ./Backend
    container_name: Backend
    ports:
      - "8080:8080"
      - "587:587"
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
  frontend:
    build:
      context: ./Frontend
    container_name: Frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./Frontend/nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    depends_on:
    - frontend
